### PR TITLE
Removed dependency on ifconfig #12

### PR DESCRIPTION
**Pull request by iommu**
Removed the dependency on ifconfig which is generally depreciated. Also this removes the need for writing to a temp file just to get the IP addr. Code from https://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib

### CODE REVIEW

**Comment by nsankethreddy** [comment]
Hey @iommu, we had tried this approach(fetching IP using getsockname()) earlier, and it doesn't seem on some OS including a Llinux leading distros,  UBUNTU 18.04 and 20.04. Which is why we chose to opt for the current approach. Although this is completely dependent on the net-tools package, it works perfectly.

**Comment by nsankethreddy** [comment]
I am closing your PR now if you feel Iv made a mistake please feel free to reopen your PR and make the required argument.

**Comment by iommu** [comment]
I had that issue too. Thats why in the code it has

**Comment by iommu** [comment]
This seems to work on MacOS and Linux (example with os.system('clear') removed and print(self.IP) added)
MacOS
image

**Comment by nsankethreddy** [comment]
It seems to work on my main OS

Screenshot from 2020-10-06 07-39-09

When when I run the same code on a VM in the same subnet it doesn't work(I don't get the required IP)

Screenshot from 2020-10-06 07-42-46

**Comment by iommu** [comment]
Hmm that's interesting it seems to be getting the ip addr 10.0.2.15 from enp0s3. I think that has something to do with s.getsockName()[0]. I'll take a look

**Comment by iommu** [comment]
Ok so i've updated it to find the ip of every interface and then chose the interface starting in "192." similar to the original grep statement. So this should work better now

**Comment by nsankethreddy** [comment]
> Ok so i've updated it to find the ip of every interface and then chose the interface starting in "192." similar to the original grep statement. So this should work better now

The current version of your code is not even running on my main OS.
Screenshot from 2020-10-06 11-46-23

This is the error that shoots up.
Try fixing that.

Here, is the error in the text format
```
Traceback (most recent call last):
  File "server.py", line 150, in <module>
    s1 = serverType()
  File "server.py", line 29, in __init__
    interfaceIP = socket.inet_ntoa(fcntl.ioctl( 
OSError: [Errno 99] Cannot assign requested address
```

**Comment by sakshi2912** [comment]
> Ok so i've updated it to find the ip of every interface and then chose the interface starting in "192." similar to the original grep statement. So this should work better now

@iommu looks like interfaceIP is always 127.0.0.1, and is not checking for "startswith('192.')"
Screenshot from 2020-10-06 12-03-29

**Comment by nsankethreddy** [comment]
Also, @iommu open a new issue in the issue section that you are currently trying to fix, before you continue working on this :)

**Comment by iommu** [comment]
I created the issue and added error handling

**Comment by nsankethreddy** [comment]
Hey, @iommu the current version works on my system, @sakshi2912  will be merging it after checking the code on Mac OS.

**Comment by iommu** [comment]
Actually i just checked it and it doesn't seem to work yet. I'll do a bit more work and get back to you when it works on mac

**Comment by sakshi2912** [comment]
> Actually i just checked it and it doesn't seem to work yet. I'll do a bit more work and get back to you when it works on mac

Hey @iommu, I've noticed that the library fcntl used, is not compatible with windows, and gives import errors when running on windows. Could you look into that as well?

**Comment by iommu** [comment]
Huh I thought fnctl was a default library. Anyway It's looking like a macos update has broken the method that socket uses for finding interface IP addrs so the only eazy python only way to get this data is using then external library netifaces which isn't ideal.

**Comment by iommu** [comment]
I'll look into adding the `ip` command as a backup if ifconfig is missing instead and ip is the ifconfig replacement

**Comment by sakshi2912** [comment]
> Huh I thought fnctl was a default library. Anyway It's looking like a macos update has broken the method that socket uses for finding interface IP addrs so the only eazy python only way to get this data is using then external library netifaces which isn't ideal.

Well, when I tried it on macOS it did not throw any error..

**Comment by nsankethreddy** [comment]
Hey @iommu, I realized that we cannot automatically decide an IP address for hosting the server, because it completely depends on the user for choosing the network where the server needs to be hosted on. So a menu-driven approach has been implemented.

Thank you for showing your interest in our project.

Try fixing other issues if you wish to contribute so this project :)

**Pull request closed without merging**
