### PR TITLE
Fix deprecation of ifconfig

### LINKED ISSUE #12: Remove dependency on ifconfig
ifconfig has been depreciated

### PR DESCRIPTION
**Pull request by Gituser143**
Replaced use of files and `ifconfig` with a subprocess and `hostname -I` to get host IP.

Fixes #12

### CODE REVIEW

**Comment by Gituser143** [comment]
@nsankethreddy @sakshi2912 Could I get a review?

**Comment by nsankethreddy** [comment]
This approach will not be working if the machine has multiple network interfaces, just implement a menu-driven approach for letting the user choose an IP/network for hosting the server.

**Comment by Gituser143** [comment]
@nsankethreddy Implemented a menu to allow choice of interface.

**Comment by nsankethreddy** [comment]
Good Job @Gituser143 , will merge after testing on Mac OS.

**Comment by iommu** [comment]
This seems to be broken on my computer for reference 
image
Linux 5.7.19-2-MANJARO

**Comment by iommu** [comment]
Ok so it looks like the hostname command is included in the same depreciated package as ifconfig on Arch haha as it was replaced by hostnamectl and so the hostname command isn't kept up to date.
 
`ip a` is the command that replaced ifconfig so that should probably be the command that is used for this section anyway.

**Comment by Gituser143** [comment]
> Ok so it looks like the hostname command is included in the same depreciated package as ifconfig
Oof now that's an issue :P

**Comment by iommu** [comment]
Even better it doesn't seem to be working on MacOS for me. They seem to be using an entirely different command from BSD that doesn't have the ability for showing IP. 

I thing you need a try, catch for `ifconfig` then `ip a` so that you can get the IP for older linux / MacOS then if that fails then new linux

**Comment by Gituser143** [comment]
@iommu I just tried it out with ip and grep. Could you verify is this works on mac?

**Comment by iommu** [comment]
Does work on my Linux. Maybe split the if platform == ... into mac and linux. Then use an ifconfig subprocess on MacOS and then this new ip subprocess on linux

**Comment by Gituser143** [comment]
> Maybe split the if platform == ... into mac and linux.

This is fair. I'll get to it! Would you suggest using `ifconfig` on MacOS though?

**Comment by iommu** [comment]
ifconfig still seems to be supported on MacOS.

**Comment by nsankethreddy** [comment]
> @iommu I just tried it out with `ip` and `grep`. Could you verify is this works on mac?

This implementation is not very different from the current implementation. The whole of this issue was to use something cleaner than grepping for IP in other commands.

**Comment by nsankethreddy** [comment]
But nevertheless, this works fine on Mac and Linux. So I will merge this.

**Comment by iommu** [comment]
While I agree I'd like to have this achieved with only python libraries this a) solves the issue of ifconfig depreciation and b) doesn't use a temporary file to transfer the command output to the python runtime. So it is definitely better than before

**Pull request merged**
