### PR TITLE
Adding file transfer feature #15

### PR DESCRIPTION
**Pull request by aparnagopalakrishnan432**
Sending files from client to server and vice versa.

Sender types <file:path_to_file> and the file is sent to the receiver

For better understanding of file transfer place client and server in different directories.

can be extended to image files like in issue#14

### CODE REVIEW

**Comment by sakshi2912** [comment]
Hey! That works great!

**Review by sakshi2912 — CHANGES_REQUESTED** [review]
Can you change the code to receive all the files into a folder called "Proximity_files".

**Comment by sakshi2912** [comment]
Could you also update the README with this added feature ? @aparnagopalakrishnan432

**Comment by aparnagopalakrishnan432** [comment]
I added the required changes and separated client and server files in Proximity_files as well.
Let me know if I should update something else too.

**Review by sakshi2912 — APPROVED** [review]

**Comment by nsankethreddy** [comment]
Hey, @aparnagopalakrishnan432 I had commented out the part of your code that used to close the connection everytime there was  a wrong file address was given.
But that seems to have been broken the file transfer feature, could you look into this issue?

**Comment by aparnagopalakrishnan432** [comment]
okay i'll check it out...
Should I just send a message saying 'file not available' or something like that and then continue receiving?

**Comment by nsankethreddy** [comment]
> okay i'll check it out...
> Should I just send a message saying 'file not available' or something like that and then continue receiving?

Yeah that'll be perfect, as a bonus you could also inform other nodes (the nodes that are receiving the file) as of who is sending the file. The message could be like "Ash has sent a file" instead of "file received successfully".

**Pull request merged**
