### PR TITLE
Added functionality for sending images bidirectionally

### PR DESCRIPTION
**Pull request by RAMYA-CP**

### CODE REVIEW

**Comment by sakshi2912** [comment]
hey @RAMYA-CP , the code doesn't seem to work with images. I believe this approach would work for sending files rather than images.

Here are some screenshots for your reference:

It gives a success message , but the sender gets disconnected form the server.
image

This is the image sent:
image

This is the image received:
image

**Comment by RAMYA-CP** [comment]
Hey Sakshi, I am not sure why is happening it works in windows for both jpg and png files though 
CLIENT
image
SERVER
image

**Comment by sakshi2912** [comment]
> Hey Sakshi, I am not sure why this is happening it works in windows for both jpg and png files though
> CLIENT
> image
> SERVER
> image

I see, is the entire image received ?

**Comment by RAMYA-CP** [comment]
Hey I have changed the file chunk size to 512 hope this works, please do let me know!

**Comment by sakshi2912** [comment]
> Hey I have changed the file chunk size to 512 hope this works, please do let me know!

Yup it works now!

**Pull request merged**
